version: 0.2 # code build 組建規格版本 0.2，勿隨意修改
env:
  variables:
    VERSION: 4
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo 'pre_build'
  build:
    commands:
      - echo 'build'
      - echo $VERSION
  post_build:
    commands:
      - echo 'post_build'
